
class FileIO:
    def __new__(cls, file: str, mode: str) -> "FileIO": ...

    def __enter__(self) -> "FileIO": ...
    def __exit__(self) -> None: ...

    def read(self, size: int | None = None) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def close(self) -> None: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int) -> None: ...
    def flush(self) -> None: ...

SEEK_SET: int
SEEK_CUR: int
SEEK_END: int
