from typing import Callable

class LineProfiler:
    def __init__(self): ...

    def add_function(self, func: Callable) -> None: ...

    def runcall(self, func: Callable, *args, **kw) -> None: ...

    def print_stats(self) -> None: ...
