from typing import Literal
from vmath import vec2, color32
from cute_png import Image

def read_axis(self) -> vec2: ...

def read_button(self, index: Literal[0, 1, 2, 3, 4, 5], ttl_ms: int = 10) -> bool: ...
def read_all_buttons(self, out_list: list[bool], ttl_ms: int = 10) -> None: ...
def clear_button(self, index: Literal[0, 1, 2, 3, 4, 5]) -> None: ...
def clear_all_buttons(self) -> None: ...

def read_buzzer_freq(self) -> int: ...
def read_buzzer_volume(self) -> float: ...
def write_buzzer_freq(self, freq: int) -> None: ...
def write_buzzer_volume(self, volume: float) -> None: ...

def write_fb0(self, image: Image) -> None: ...

def read_led(self, index: Literal[0, 1, 2, 3]) -> color32: ...
def write_led(self, index: int, color: color32) -> None: ...
def write_leds(self, _0: color32 | None, _1: color32 | None, _2: color32 | None, _3: color32 | None) -> None: ...
