#pragma once
// generated by prebuild.py

namespace pkpy{
    extern const char kPythonLibs__enum[];
    extern const char kPythonLibs__long[];
    extern const char kPythonLibs__set[];
    extern const char kPythonLibs_bisect[];
    extern const char kPythonLibs_builtins[];
    extern const char kPythonLibs_cmath[];
    extern const char kPythonLibs_collections[];
    extern const char kPythonLibs_colorsys[];
    extern const char kPythonLibs_datetime[];
    extern const char kPythonLibs_functools[];
    extern const char kPythonLibs_heapq[];
    extern const char kPythonLibs_itertools[];
    extern const char kPythonLibs_pickle[];
    extern const char kPythonLibs_this[];
    extern const char kPythonLibs_typing[];
}    // namespace pkpy
