#include "../c-periphery/src/gpio.h"
// #include "../c-periphery/src/i2c.h"
// #include "../c-periphery/src/led.h"
// #include "../c-periphery/src/mmio.h"
#include "../c-periphery/src/pwm.h"
// #include "../c-periphery/src/serial.h"
// #include "../c-periphery/src/spi.h"
#include "../c-periphery/src/version.h"
